### ISSUE TITLE
Issue with GeneAssign.py/Eta_sampler.py - IndexError

### ISSUE THREAD

**Issue by vaxherra** [chrisquince/DESMAN#19]
When I run the last step from your workshop at https://github.com/chrisquince/CopenhagenWorkshop/blob/master/Tutorials/StrainResolution.md

I repeatedly got **IndexError**s: 

`/Volumes/<my_private_path_here>/DESMAN//desman/GeneAssign.py Cluster0_coremean_sd_df.csv Gamma_star.csv Cluster0_gene_cov.csv Eta_star.csv -m 20 -v Cluster0sel_var.csv -o Cluster0000 --assign_tau`

`Traceback (most recent call last):`
 ` File "/Volumes/<my_private_path_here>/DESMAN//desman/GeneAssign.py", line 335, in <module>
    main(sys.argv[1:])`
 ` File "/Volumes/<my_private_path_here>/DESMAN//desman/GeneAssign.py", line 266, in main
    etaSampler.update()`
 ` File "/<my_private_path_here>/DESMAN/desman/Eta_Sampler.py", line 214, in update
    self.ll = self.logLikelihood()`
  `File "/<my_private_path_here>/DESMAN/desman/Eta_Sampler.py", line 187, in logLikelihood
    self.gene_ll[c] += self.eta_log_prior[self.eta[c,g]]`

`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`

I give you and example for one of my clusters. (dropbox link)

https://www.dropbox.com/sh/6yp751keef2i5yt/AADyIZSin9cuiJusX_pWgB1qa?dl=0

So far an entire pipeline worked (with some problems here and there) like charm, but this final accessory genome assignment fails.

I execute the code with:
`cd test #from the folder in dropbox`
`python /<my_desman_repo_location>/desman/GeneAssign.py Cluster0_coremean_sd_df.csv Gamma_star.csv Cluster0_gene_cov.csv Eta_star.csv -m 20 -v Cluster0sel_var.csv -o Cluster0000 --assign_tau`

**Comment by chrisquince** [comment]
Sorry to take so long to get around to this, but I believe that bug is fixed now.
