### ISSUE TITLE
conda install

### ISSUE THREAD

**Issue by micromania2** [chrisquince/DESMAN#22]
Any plans to get this into conda for a one click install?

**Comment by meren** [comment]
I am jumping in, I hope Chris doesn't mind:

There is currently an effort to convert the codebase to Python 3, and we will be happy to also make installation and utilization of the tool much more easier.

Thanks!

**Comment by micromania2** [comment]
Awesome, great news and thanks for the quick reply. When do you think that will be completed?

Thanks again!

**Comment by meren** [comment]
My colleagues (Ozcan Esen and Evan Kiefl) finished converting the codebase to Python 3, and confirmed everything is working. They will soon send a pull request for Chris to investigate. Once the codebase is settled, and Chris is happy, we can work on an easy installation scenario.

While I am not comfortable giving an estimate on others' behalf, I don't think it would take a lot. That said, I am not sure if we can deliver that in less than 2 weeks, since there is always another 10 things to do on the side :)


Best wishes,

**Comment by micromania2** [comment]
I know how that goes all too well. Things always take longer than expect. 

God Speed Meren! :)

**Comment by micromania2** [comment]
Hi Meren,

Excited to install/use Desman with conda install. Do you still think it will be completed soon?

**Comment by meren** [comment]
Good reminder :) Thank you!

@chrisquince, we want to deliver this, but we need to have a tagged version of the master repository.

do I have your permission to tag the current `master` as `v2.0`? or if you have anything minor to add to/remove from the current `master` we can wait for that.


Best,

**Comment by chrisquince** [comment]
Hi Meren,

There are a few minor python3 fixes in the scripts that need committing first. I will add those to the current master later on today and let you know when it is ready to tag.

Thanks,
Chris

**Comment by meren** [comment]
Done! Thank you, @chrisquince. There will be a brew package for this tagged version very soon.

**Comment by micromania2** [comment]
and a conda package for us conda users? Too much too soon? :)

**Comment by meren** [comment]
Let's go step by step. Once there is a brew package, conda will be rather straightforward I presume.

**Comment by johnne** [comment]
Hi all,
I've been working on getting desman ready for use in a snakemake workflow I'm using. As part of that I've also taken the first steps to add a desman recipe to the bioconda channel. Please see PR #26.

All the best,
John

**Comment by meren** [comment]
Excellent, John! Thanks for this :)

**Comment by johnne** [comment]
No problem :). If you add a release for the latest merge I will update the bioconda recipe and make a pull request to have it added to the channel.

**Comment by chrisquince** [comment]
Hi John, I have created a new version 2.1 of that merge after checking the complete example again. I need to automate that!
