### ISSUE TITLE
Python type issue

### ISSUE THREAD

**Issue by njdbickhart** [chrisquince/DESMAN#29]
https://github.com/chrisquince/DESMAN/blob/e960b197dc0cd2db6e7f54db1146c23f252e6ac1/scripts/GetVariantsCore.py#L89

Perhaps it's just my version of python, but this line creates a type "float" that cannot be used in future index or range functions. A cast to an "int" would fix this bug.

**Comment by chrisquince** [comment]
Thanks, yes that is something that became a problem after switch to python3, I have fixed it and will also add others casts as needed following testing.

Sorry for the slow response, but better late than never!
