### ISSUE TITLE
bam-readcount give too many errors for strain dataset

### ISSUE THREAD

**Issue by liuxianghui** [chrisquince/DESMAN#3]
After I run the bam-readcount.  I found there are too many errors. It seems to due to the single-end mapping quality. What is SM tag is in BAM? Please suggest,
[xianghui@merlion Counts]$ ls -lat Sample803*
-rw-r--r-- 1 xianghui research 1024275175 Oct  4 15:29 Sample803_sub.err
-rw-r--r-- 1 xianghui research   71760285 Oct  4 15:29 Sample803_sub.cnt

[xianghui@merlion Counts]$ head Sample803_sub.err
Minimum mapping quality is set to 20
WARNING: In read gi|91209055|ref|NC_007946.1|Escherichia_coli_UTI89_chromosome+plasmid,complete_genome_nr5269249: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|556503834|ref|NC_000913.3|Escherichia_coli_str._K-12_substr._MG1655,complete_genome_nr7186065: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|556503834|ref|NC_000913.3|Escherichia_coli_str._K-12_substr._MG1655,complete_genome_nr489599: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|556503834|ref|NC_000913.3|Escherichia_coli_str._K-12_substr._MG1655,complete_genome_nr2496235: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|91209055|ref|NC_007946.1|Escherichia_coli_UTI89_chromosome+plasmid,complete_genome_nr9334353: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|556503834|ref|NC_000913.3|Escherichia_coli_str._K-12_substr._MG1655,complete_genome_nr8824826: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|556503834|ref|NC_000913.3|Escherichia_coli_str._K-12_substr._MG1655,complete_genome_nr4303092: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|556503834|ref|NC_000913.3|Escherichia_coli_str._K-12_substr._MG1655,complete_genome_nr4105858: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.
WARNING: In read gi|556503834|ref|NC_000913.3|Escherichia_coli_str._K-12_substr._MG1655,complete_genome_nr11646158: Couldn't find single-end mapping quality. Check to see if the SM tag is in BAM.

**Comment by chrisquince** [comment]
Hi,

This is nothing to worry about:

https://www.biostars.org/p/93418/

 "All it means is that the single-end mapping quality field of the output will not be populated."

We don't use mapping qualities anyway.

Thanks,
Chris

**Comment by liuxianghui** [comment]
So this will not affect the count? I thought if the quality is below 20, it will not be added to number of counts for this nucleotide position.
